name: Continuous Deployment
on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: update
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Hugging Face Hub
        run: pip install -U huggingface_hub

      - name: Deployment To Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Space pehle se bana hua hai, isliye sirf direct files upload karenge
          hf upload Syestembae/my-model-app . . --repo-type=space --commit-message="Deploy updated gradio-lite app"
