name: Continuous Deployment
on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Hugging Face Tool
        run: |
          pip install --upgrade pip
          pip install huggingface-hub

      - name: Deployment To Hugging Face
        env:
          HF: ${{ secrets.HF_TOKEN }}
        run: |
          git pull origin update || true
          
          # Direct hf commands bina kisi Makefile dependencies ke
          hf auth login --token $HF
          
          hf upload sheikhmar90-plitch/my-model-app ./App . --repo-type=space --commit-message="Sync App files" || hf upload sheikhmar90/my-model-app ./App . --repo-type=space --commit-message="Sync App files"
          hf upload sheikhmar90-plitch/my-model-app ./Model ./Model --repo-type=space --commit-message="Sync Model" || hf upload sheikhmar90/my-model-app ./Model ./Model --repo-type=space --commit-message="Sync Model"
          hf upload sheikhmar90-plitch/my-model-app ./Results ./Metrics --repo-type=space --commit-message="Sync Metrics" || hf upload sheikhmar90/my-model-app ./Results ./Metrics --repo-type=space --commit-message="Sync Metrics"
