name: Model Training and Deployment

on:
  push:
    branches: [ main ]

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: make install

    - name: Format Code
      run: make format

    - name: Train Model
      run: make train

    - name: Evaluate Model
      run: |
        # Humne 'cml' tool ko hata diya hai taake koi error na aaye
        echo "## Model Metrics" > report.md
        cat Results/metrics.txt >> report.md
        echo "" >> report.md
        echo "## Confusion Matrix Plot" >> report.md
        echo "![Confusion Matrix](Results/model_results.png)" >> report.md
        
        # Yeh line aapki report ko seedha GitHub screen par print kar degi
        cat report.md >> $GITHUB_STEP_SUMMARY

    - name: Update Branch
      env:
        NAME: ${{ secrets.USER_NAME }}
        EMAIL: ${{ secrets.USER_EMAIL }}
      run: |
        make update-branch USER_NAME="$NAME" USER_EMAIL="$EMAIL"

    - name: Push to Hugging Face
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        git config --global user.name "CI Bot"
        git config --global user.email "bot@example.com"
        git remote add hf https://huggingface.co{{ secrets.USER_NAME }}/update-branch
        git push --force hf update:main
